I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/player_assessment.rpy", line 785, in script
    $ persistent.q4_overall_grade = int(lesson_10_weighted_score + q3_exam_weighted_score)
  File "game/player_assessment.rpy", line 785, in <module>
    $ persistent.q4_overall_grade = int(lesson_10_weighted_score + q3_exam_weighted_score)
NameError: name 'q3_exam_weighted_score' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/player_assessment.rpy", line 785, in script
    $ persistent.q4_overall_grade = int(lesson_10_weighted_score + q3_exam_weighted_score)
  File "D:\installedApps\Ren'py\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\installedApps\Ren'py\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/player_assessment.rpy", line 785, in <module>
    $ persistent.q4_overall_grade = int(lesson_10_weighted_score + q3_exam_weighted_score)
NameError: name 'q3_exam_weighted_score' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
CodeDreams 1.0
Fri Feb  2 01:28:56 2024
