I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/player_assessment.rpy", line 329, in script
    $ persistent.written_works = (lesson_1_quiz1 + lesson_2_quiz2 + lesson_3_quiz3)/30
  File "game/player_assessment.rpy", line 329, in <module>
    $ persistent.written_works = (lesson_1_quiz1 + lesson_2_quiz2 + lesson_3_quiz3)/30
NameError: name 'lesson_1_quiz1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/player_assessment.rpy", line 329, in script
    $ persistent.written_works = (lesson_1_quiz1 + lesson_2_quiz2 + lesson_3_quiz3)/30
  File "D:\installedApps\Ren'py\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\installedApps\Ren'py\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/player_assessment.rpy", line 329, in <module>
    $ persistent.written_works = (lesson_1_quiz1 + lesson_2_quiz2 + lesson_3_quiz3)/30
NameError: name 'lesson_1_quiz1' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
CodeDreams 1.0
Thu Feb  1 04:52:51 2024
